### ISSUE TITLE
Missing exception handling :)

### ISSUE THREAD

**Issue by abhilash1in** [msamogh/zed-ros-to-asl-converter#1]
https://github.com/msamogh/zed-ros-to-asl-converter/blob/6e3e3e90636aede6221901955674c193b1742761/calibration_converter.py#L12

https://github.com/msamogh/zed-ros-to-asl-converter/blob/6e3e3e90636aede6221901955674c193b1742761/calibration_converter.py#L18

**Comment by msamogh** [comment]
Pull requests are welcome :)
